### ISSUE TITLE
NSFW Locomotion Permanently Handicaps Avatars

### ISSUE THREAD

**Issue by technoalli3** [LastationVRChat/NSFW-GoLoco#10]
When adding the prefab to the avatar via VRCFury, the locomotion system causes random parts of the armature to invert, fold, or otherwise behave improperly when extended or articulated. This behaviour continues even after the prefab has been removed from the avatar, and all assets for said prefab deleted from the project.

To reproduce:
1. Import unitypackage.
2. Find the prefab in the folder.
3. Drag under avatar root.
4. Enter VRChat in VR mode and observe. May not happen to all avatars, but it happened to 2 out of 2 avatars I tried it on.

To fix:
1. Drag a new copy of your avatar prefab into the hierarchy.
2. Copy and paste as child any elements that were added after the fact.
3. Put the FX layer into the animator controller.
4. Add a new avatar descriptor to your new prefab.
5. Copy component from other avatar by right clicking the 3 dots and clicking copy component.
6. Click the 3 dots on the avatar descriptor in the new avatar, and click paste as values.
7. Find the viseme section, the eye rotation selection, and make sure to swap the references for the body and eye roots under the NEW avatar; they will still be referencing the old one.
8. Done; Avatar should behave as before, but without bone crunching.

**Comment by KuryKat** [comment]
Please download the [latest release](https://github.com/LastationVRChat/NSFW-Locomotion/releases/tag/v1.8.3-NSFW-0.0.1) and try again, if you still having issues, reopen this issue or open a new issue!
