### ISSUE TITLE
VRFury

### ISSUE THREAD

**Issue by WindingDuke77** [LastationVRChat/NSFW-GoLoco#2]
The VRFury Prefabs will put the menu option inside of the root menu, and not in the sub menu.
To fix this you would have to do something like the follow;

![image](https://github.com/LastationVRChat/NSFW-GoLoco/assets/64500127/75728294-85a8-45bd-a3c5-2de801f3db32)
![image](https://github.com/LastationVRChat/NSFW-GoLoco/assets/64500127/f8e24c0e-c396-4bc3-a35b-8bd62496b5ac)

**Comment by KuzuriYager** [comment]
I am not seeing the problem our version does not use "GoAllMainMenu" it just uses "GoAllMenu" so if you have the former then you still have OG Gogo Loco in your project.
