### ISSUE TITLE
cross one leg pose 231

### ISSUE THREAD

**Issue by zee-wolf** [LastationVRChat/NSFW-GoLoco#4]
go_cross_one_leg pose, 231 in blend tree is broken, I redid the state machine in the pose controller, (it was disorganized), but it still doesn't work

**Comment by KuryKat** [comment]
This has been fixed on the [latest release](https://github.com/LastationVRChat/NSFW-Locomotion/releases/tag/v1.8.3-NSFW-0.0.1)

If you encounter any more issues feel free to open a new issue report!
