### ISSUE TITLE
When will the update with the pose and animation of your latest version?

### ISSUE THREAD

**Issue by Yiffabasically** [LastationVRChat/NSFW-GoLoco#5]
Don't worry i can wait, just wondering when will it finish? (possibly and not guranteed date)

**Comment by KuzuriYager** [comment]
this is a side project and not a main project so any work on this is done at random in massive bursts.

**Comment by KuryKat** [comment]
We have *just* released the [new version](https://github.com/LastationVRChat/NSFW-Locomotion/releases/tag/v1.8.3-NSFW-0.0.1) today! Please try it out and have fun!
