### ISSUE TITLE
Not laoding right

### ISSUE THREAD

**Issue by shot666** [LastationVRChat/NSFW-GoLoco#6]
I want to use this the animated version but there is an issue. When I add it to my avatar like I would the 'poses only' I get missing files when trying to upload it.

**Comment by KuryKat** [comment]
Please download the [latest release](https://github.com/LastationVRChat/NSFW-Locomotion/releases/tag/v1.8.3-NSFW-0.0.1) and try again, if you still having issues, reopen this issue or open a new issue!
