### ISSUE TITLE
Installation on Avatar replaces pre existing expression menu options for toggles.

### ISSUE THREAD

**Issue by Pwetzelz** [LastationVRChat/NSFW-GoLoco#7]
This issue is persistent on every version I tried. I used the VRCFURY installer to put it on an avatar, and when I load it in game the options are all on the main menu and aren't foldered. Second issue is the poses just doing the default missing pose type of pose, and none of them work. On 1.7.8 with the.... two things one of them being poses as I don't remember the name as soon as I go to say it, that works.
Edit: Emotes.

**Comment by KuryKat** [comment]
Please download the [latest release](https://github.com/LastationVRChat/NSFW-Locomotion/releases/tag/v1.8.3-NSFW-0.0.1) and try again, if you still having issues, reopen this issue or open a new issue!
