### ISSUE TITLE
Changing height position is broken

### ISSUE THREAD

**Issue by MikuChan3D** [LastationVRChat/NSFW-GoLoco#8]
When using the Radial Puppet to change my height when using the posses, it breaks the pose.

**Comment by HalcyonsOmen** [comment]
I also discovered this issue, however I also found that you can use the height dial and height arrows from the previous menus which will work. Avoid the height dial in the 18+ poses.

**Comment by MikuChan3D** [comment]
yeah I'm very aware of that but it's annoying. Still so 3 months later

**Comment by KuzuriYager** [comment]
We are working on a new version to come out soon, this project has been on ice due to it being a side project and not a mianline project.

**Comment by tw1l1ght** [comment]
wouldnt it work to take gogo 1.83 & "just" putting the poses/animations into it? (via c&p/gogo controller-editing or furys/MAs menu-move? (in the meanwhile)

ye, no more "one click" solution but still...

**Comment by KuryKat** [comment]
We _have_ "just" done that, but we are tweaking things for it to work the best way possible.

Please be patient, we are cooking good meal.

**Comment by KuryKat** [comment]
We have released the [new version](https://github.com/LastationVRChat/NSFW-Locomotion/releases/tag/v1.8.3-NSFW-0.0.1) today! Please try it out and have fun!
